### ISSUE TITLE
Baruwa uwsgi problem

### ISSUE THREAD

**Issue by gsnick** [akissa/baruwa#77] opened 2015-09-08 16:36 UTC
Hello,

After installing nginx+uwsgi I see "Internet server error" when accessing Baruwa UI.
There is the following message in  /var/log/uwsgi/uwsgi-baruwa.log log:

--- no python application found, check your startup logs for errors ---

I followed the instructions from https://pythonhosted.org/baruwa/community/nginx-uwsgi.html.
Could someone advice what I need to check in order to fix the issue?

Thank you advance!

**Comment by akissa** [comment] 2015-09-08 16:43
Use the mailing list for setup issue, this is not a bug or feature request closing.

**Closed by akissa** 2015-09-08 16:43 UTC
